# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d9a5bec3b6f5b4fdc632e8bbdfe10c01cce09d2c63c48ed38ca771b930176cf5de5617ea6cefaec6f2ad5feda5d0d0b10168199267e86dd9c3e35dd9cf358b0

test:
  secret_key_base: 1dfff56af70f2a5643ce8b6efbd33ffeca4d0eab12c04a2bd4e890c6f9045e3696482aea017a7bbcd7d895dd592aa91cff94514951381e3f0f2b29f280a8ca4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
